{{- if .Values.guestbook }}
{{- if .Values.guestbook.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.guestbook.namespace }}
    server: {{ .Values.server }}
  project: {{ .Values.projectName }}
  source:
    path: guestbook
    repoURL: git@github.com:BechirLandolsi/argocd-appofapps-example.git
    targetRevision: {{ .Values.guestbook.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end }}
{{- end }}