kind: Secret
apiVersion: v1
metadata:
  name: github-ssh-creds
  namespace: openshift-gitops
  uid: aca32aa9-4d55-4af2-ab44-3a8109137a43
  resourceVersion: '3319582'
  creationTimestamp: '2025-08-29T09:05:51Z'
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-08-29T09:05:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:sshPrivateKey': {}
          'f:url': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:argocd.argoproj.io/secret-type': {}
        'f:type': {}
data:
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUE0Y3N0eTR2d1FDeG1jeGErUHdVSUVFbUVsNjBqcERzQzk4R2o0UjZUbjU3SWJMblZ3YXhmCnRuVm02V3U5OFZwUFZZc2xZU0ZodjMybmdBZUE2enhpSWhSL00zUERzN1NnSVVFNFg3TXJENFJiYkdoVnFud0pWSDlHR1IKVURNSzM4TUw3U2NHZGJvWUV6U3hlRkpKQmFna0JVeFNrSkFWOHFNcEVHNS9OYlFvMndKN2hOV1ozeHpiVXROR2hKcmFGVQpCLzB2NGhXZlY4MWpBajFzdTkwVUtqV2RTRDgwY21ySmxkQWtIcEZRTG4wblg0OGUzV2RmeWcrRDRreUFhY2lTdjVCaTlWCjA1M0pmL3lXK1kvbjJSek1xRU4ycnl1WUFIZ3F4MkY5QjBBS0hDQXdjQjc3ZDM2ZVoybVoyQXdUNnlQY2RIdVdkbk9zdzMKWU9wL3AyWFd3d0FBQThCbWlFbHdab2hKY0FBQUFBZHpjMmd0Y25OaEFBQUJBUURoeXkzTGkvQkFMR1p6RnI0L0JRZ1FTWQpTWHJTT2tPd0wzd2FQaEhwT2Zuc2hzdWRYQnJGKzJkV2JwYTczeFdrOVZpeVZoSVdHL2ZhZUFCNERyUEdJaUZIOHpjOE96CnRLQWhRVGhmc3lzUGhGdHNhRldxZkFsVWYwWVpGUU13cmZ3d3Z0SndaMXVoZ1ROTEY0VWtrRnFDUUZURktRa0JYeW95a1EKYm44MXRDamJBbnVFMVpuZkhOdFMwMGFFbXRvVlFIL1MvaUZaOVh6V01DUFd5NzNSUXFOWjFJUHpSeWFzbVYwQ1Fla1ZBdQpmU2Rmang3ZFoxL0tENFBpVElCcHlKSy9rR0wxWFRuY2wvL0piNWorZlpITXlvUTNhdks1Z0FlQ3JIWVgwSFFBb2NJREJ3Ckh2dDNmcDVuYVpuWURCUHJJOXgwZTVaMmM2ekRkZzZuK25aZGJEQUFBQUF3RUFBUUFBQVFBU2ZhZ2Ziak5ibmdjNXo1ZisKNHpPWTJkeHc2MjNxeWlaaEVjdVE2UWNmNEVuN2xYQnE3dW5ic0Z1Z0xBR2ZIVTAzN1RBL2R4TmhNaklnYXZ6a3hzb21qbApVb2FvZVJWTzUwS3JvcUpDc1hsemhCZFgzbWUwZnNVb3YwQytONS9oV1VERnlCZGdWc0FYK28yNkU4c0ZHcEx3bUNKKzBqCjNwNC9DOTlyNldNRTNSd3pZa29NQ3ZsUVh0T21GNE9Mb054S2poNHNQTlo3L1ZiWnpxNlUwNjNJRVJWM3JpWE9lR2NaU1AKeEwrSTBGNU8xYnNsRm1Fa1NPNUNjM05UeVcva25jREZvcytOQlRZMkZMWW5Pa2FFbTFlVW1IZFAyODU2VGdjMG5Jd3A0ZAphV3VDTHdvN2h4dm9wM2U5MkZ2T1FXeHFvcXdpcytROUlpNkN5M0ROUUIweEFBQUFnUUM3WXltYjVZdVRLeVZtekx2cVZEClFWdkdiWEdPeENYenlRaFdMeUdPUjhtNHN4UzBHZGhraWNLYkNuUlNtNk45bEJYOEQzYUQrNUQ2K0ZRUXQ3aVRQSDNSdy8Kc0NIcm1MclBGaTd2Z2VPN2d3MWVKQXZkRGhQRmVMcG5VWlczZlVuTEhOWWhHUmlUSzR0eWdMb2pmbXl5K2daTFdGNDZkegpkbHNJdEw1OUdjbFFBQUFJRUErVnZkR3pLOVdzZlpxT3lTQ3RmdFBNQlozZXFxcnI5Z0tYSHo5Wkl4bDBDRGZRVURQRll2CmVuUHo5NkhCMmZiMHlMOWxMR1lEMGZwcDdnZWlRR2JjTXo0WUkzTEZiYll1K2szb2lNazVnSU4xNTRZaURidHVad2dIcDIKQTlHSTVUWkcyZy9tc3ptby95ZTNxQ2FMcVgwb0lUbGd1T1VGS0M1NUxQVXkwZnhva0FBQUNCQU9mT3BhZzlEbWxiemQrNQpLV2JsSTNqQnJoQyt3RDBjMk9PT05lUHdqOWRjdEV0dy92Qm11alZ2L0tFRW5jNjVqL0VVUjBjRWwvSHNiRXM4WU9ZV2lJCnZaZ3dSeGhHcmg0WVlqUDhDT3dKcVRRNVZiN1RVNkdvSmdac21vb0c3RFhtVnMxQWtHREl5RFZuWFYrb2c3Y1kvdUhZeUEKOWtpMExkcW9ZTzNFc0IvckFBQUFDbWRwZEd4aFlpNWpiMjA9Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  url: Z2l0QGdpdGh1Yi5jb206QmVjaGlyTGFuZG9sc2kvYXJnb2NkLWFwcG9mYXBwcy1leGFtcGxlLmdpdA==
type: Opaque